apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-fashion-recommander
  labels:
    app: flasknode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flasknode
  template:
    metadata:
      labels:
        app: flasknode
    spec:
      containers:
      - name: flasknode
        image: icr.io/smartfr/smartfr
        imagePullPolicy: Always
        ports:
          - containerPort: 5000
