# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: smart-fashion-recommander 
spec:
  ports:
    - port: 5000
      targetPort: 5000
  type: NodePort
  selector:
    app: flasknode

